### ISSUE TITLE
De-biased L1 calibration error estimator

### ISSUE THREAD

**Issue by tonyduan** [AnanyaKumar/calibration#2]
Hi Ananya,

Thanks for this excellent work. Read it again recently, and I was hoping there'd be code for the de-biased L1 calibration error proposed in Definition G.3 of the Appendix for this paper.

Specifically I'm trying to recreate Figure 12 in the paper. Recently I ran a simulation which found the de-biased estimator actually achieves _worse_ MSE than the plugin estimator. [[Code Here]](https://gist.github.com/tonyduan/7361badacdd78d20950cc25da01ea696).

![foo](https://user-images.githubusercontent.com/1163598/88597500-28c6cb80-d01c-11ea-8c00-44203c6ccb95.png)

Tony

**Comment by AnanyaKumar** [comment]
Hi Tony,

Thanks for reaching out! I loaded your code into Colab and found a couple
of things that need to be fixed. Specifically, we want:

mc_samples = np.random.randn(n_bins)
...
mc_ece = np.mean(np.average(np.abs(p_per_bin - mc_samples), axis=0
, weights=n_per_bin))
In particular, the formula in Definition G.3 generates a normal for each
bin (not for each sample as in line 36 of the gist. Also, line 39 of the
gist takes y_hat_per_bin - mc_samples, but we want p_per_bin - mc_samples
(the formula has s_k - R_k). I couldn't load one of your libraries, but I
tried this and it seems to give a better estimate of the ECE on your
example - let me know if you observe something different.

Our library https://pypi.org/project/uncertainty-calibration/ or
https://github.com/p-lambda/verified_calibration should be able to do this
if you call get_ece in
https://github.com/p-lambda/verified_calibration/blob/master/calibration/utils.py
with
the option debias=True. Let me know if that works for you.

Thanks,
Ananya

**Comment by AnanyaKumar** [comment]
Ah I should say you can choose to play around with the options based on the
type of model e.g. whether it is a binned model or a scaling
model. get_calibration_error tries to auto-detect whether your model is
binned or scaled, but for more control see
https://github.com/p-lambda/verified_calibration/blob/master/examples/advanced_example.py.
Then you can specify the binning strategy (uniform mass vs uniform width),
p=1 for ECE, number of bins, etc. But for a regular neural network model,
15 bins, equal width, like  https://arxiv.org/abs/1706.04599, get_ece is
the one you'd want.

**Comment by tonyduan** [comment]
> Also, line 39 of the gist takes y_hat_per_bin - mc_samples, but we want p_per_bin - mc_samples (the formula has s_k - R_k).

Perfect, this fixes the issue! Apologies for missing the code earlier; thanks a ton. 

![bar](https://user-images.githubusercontent.com/1163598/88634279-04461000-d06b-11ea-9ff8-790b36383e4d.png)

**Comment by AnanyaKumar** [comment]
Great! By the way, this repository is obsolete, so please see https://github.com/p-lambda/verified_calibration instead
